#!/usr/bin/env python
import re

stri="2L	300001	A	A/C	TT AA AA AA AA AA AA CC AA AA AA CC AA AA AA CC AA CC CC AA AA CC AA AA AA AA AA CC AA AA AA AA CC AA AA AA CC CC AA AA CC AA AA AA CC AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA CC AA AA CC AA AA AA CC AA CC AA AA AA CC AA AA AA AA AA AA AA AA AA AA AA AA CC AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA CC AA AA AA AA AA AA AA AA AA AA AA AA AA AA CC CC AA AA AA CC AA AA AA AA AA AA AA AA CC AA AA CC CC AA AA AA AA AA AA AA CC AA CC AA CC CC AA AA CC AA AA CC AA AA AA AA CC CC AA CC AA CC AA AA AA AA AA AA AA AA CC CC CC CC AA AA CC CC AA AA AA AA AA AA AA AA AA CC AA AA AA AA AA AA CC CC AA AA AA AA AA CC CC AA AA AA CC AA AA AA AA AA AA AA AA AA AA CC CC AA CC AA AA AA CC CC AA AA AA CC AA AA AA AA AA AA AA AA CC AA AA CC CC CC AA AA AA AA CC CC AA CC AA AA AA AA AA AA AA CC AA AA AA AA AA AA AA AA AA AA CC AA AA CC AA AA AA AA AA AA AA AA AA CC AA AA AA AA AA AA AA AA AA AA AA AA CC AA AA AA AA AA CC AA AA AA AA CC AA AA AA CC AA AA AA AA AA AA AA AA AA CC AA AA AA CC AA CC AA CC AA AA CC AA AA CC AA AA AA AA AA AA CC CC AA AA AA AA AA AA CC AA AA AA AA AA AA AA AA AA CC CC AA AA AA AA AA AA CC AA AA CC AA CC AA AA CC AA AA AA CC AA AA CC AA AA AA AA AA AA AA AA AA AA AA AA CC AA AA AA AA AA CC AA AA CC AA AA AA AA AA AA AA AA AA AA AA AA AA AA CC AA CC AA AA AA AA AA AA CC AA CC AA AA AA AA AA AA AA AA AA CC AA CC AA AA AA AA AA AA AA AA AA CC AA CC AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA CC AA AA AA AA AA CC AA AA AA AA CC AA"

a=re.split("\\s+",stri)
haps=a[:4]

bla=0
